export const USER_ACTIONS = {
	UPDATE: 'USER_UPDATE',
	LOGOUT: 'USER_LOGOUT'
};

export const NOTE_ACTIONS = {
	INSERT: 'NOTE_INSERT',
	UPDATE: 'NOTE_UPDATE',
	DELETE: 'NOTE_DELETE',
	EDIT: 'NOTE_EDIT'
};

export const USER_ROLES = {
	OWNER: 'OWNER',
	MANAGER: 'MANAGER'
};

export const GEO_ACTIONS = {
	UPDATE: "GEO_UPDATE",
	USE_CURRENT: "GEO_USER_CURRENT_LOCATION"
};
