export const USER_ACTIONS = {
	UPDATE: 'USER_UPDATE',
	LOGOUT: 'USER_LOGOUT'
};

export const NOTE_ACTIONS = {
	INSERT: 'NOTE_INSERT',
	UPDATE: 'NOTE_UPDATE',
	DELETE: 'NOTE_DELETE'
};

export const USER_ROLES = {
	OWNER: 'OWNER',
	MANAGER: 'MANAGER'
};
